name: Preview Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      actions: read # for dawidd6/action-download-artifact to query and download artifacts
      issues: write # for actions-cool/maintain-one-comment to modify or create issue comments
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo "Deploy to preview server"
    - name: TEST
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
